on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      repository:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_SUFFIX:
        required: true
      AZURE_UNIQUE_CODE:
        required: true

jobs:
  build:
    name: Build Service
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build Image
        run: |
          az acr build --registry $REGISTRY \
                       --resource-group $RESOURCE_GROUP \
                       --image ${{ inputs.repository }}/${{ inputs.image }}:latest \
                       --image ${{ inputs.repository }}/${{ inputs.image }}:$(echo ${GITHUB_SHA} | cut -c1-7) \
                       --file ./src/${{ inputs.project }}/Dockerfile ./src
        env:
          REGISTRY: acr${{ secrets.AZURE_SUFFIX }}${{ secrets.AZURE_UNIQUE_CODE }}
          RESOURCE_GROUP: ${{ inputs.environment }}-${{ secrets.AZURE_SUFFIX }}-${{ secrets.AZURE_UNIQUE_CODE }}
