on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  validate:
    name: Validate Environment Secrets
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment.name }}

    steps:          
      - run: |
          if [ "${{ secrets.AZURE_CREDENTIALS }}" == "" ]; then
            echo "Please set environment secret 'AZURE_CREDENTIALS' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_SUFFIX }}" == "" ]; then
            echo "Please set environment secret 'AZURE_SUFFIX' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_UNIQUE_CODE }}" == "" ]; then
            echo "Please set environment secret 'AZURE_UNIQUE_CODE' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_LOCATION }}" == "" ]; then
            echo "Please set environment secret 'AZURE_LOCATION' before running this workflow"
            exit 1
          fi
